import type { ResourceIntegrationTestConfig } from "src/tests/resource-integration.test";
import ComponentResourceCollectionRestoreService from "../services/ComponentResourceCollectionRestoreService";

const config: ResourceIntegrationTestConfig = {
  name: "Simple Components",
  description: "Test simple components with no component group dependencies",
  ServiceClass: ComponentResourceCollectionRestoreService,
  resources: [
    {
      input: {
        name: "test-component",
        display_name: null,
        description: null,
        created_at: "2025-01-01T00:00:00.000Z",
        updated_at: "2025-01-01T00:00:00.000Z",
        id: 100001,
        schema: {
          page_config: {
            type: "bloks",
            pos: 0,
            required: true,
            minimum: 1,
            maximum: 1,
            restrict_type: "",
            restrict_components: true,
            component_whitelist: ["page_config"],
            id: "test-field-id-1",
          },
          body: {
            type: "bloks",
            id: "test-field-id-2",
            pos: 1,
          },
        },
        image: null,
        preview_field: null,
        is_root: true,
        preview_tmpl: null,
        is_nestable: false,
        all_presets: [],
        preset_id: null,
        real_name: "test-component",
        component_group_uuid: null,
        color: null,
        icon: null,
        internal_tags_list: [],
        internal_tag_ids: [],
        content_type_asset_preview: null,
        metadata: {},
      },
      expectedApiCall: {
        endpointSuffix: "components",
        body: {
          component: {
            name: "test-component",
            display_name: null,
            description: null,
            created_at: "2025-01-01T00:00:00.000Z",
            updated_at: "2025-01-01T00:00:00.000Z",
            id: 100001,
            schema: {
              page_config: {
                type: "bloks",
                pos: 0,
                required: true,
                minimum: 1,
                maximum: 1,
                restrict_type: "",
                restrict_components: true,
                component_whitelist: ["page_config"],
                id: "test-field-id-1",
              },
              body: {
                type: "bloks",
                id: "test-field-id-2",
                pos: 1,
              },
            },
            image: null,
            preview_field: null,
            is_root: true,
            preview_tmpl: null,
            is_nestable: false,
            all_presets: [],
            preset_id: null,
            real_name: "test-component",
            component_group_uuid: null,
            color: null,
            icon: null,
            internal_tags_list: [],
            internal_tag_ids: [],
            content_type_asset_preview: null,
            metadata: {},
          },
          publish: 1,
        },
      },
      mockResponse: {
        data: {
          component: {
            name: "test-component",
            display_name: null,
            description: null,
            created_at: "2025-01-01T00:00:00.000Z",
            updated_at: "2025-01-01T00:00:00.000Z",
            id: 200001, // New ID after restoration
            schema: {
              page_config: {
                type: "bloks",
                pos: 0,
                required: true,
                minimum: 1,
                maximum: 1,
                restrict_type: "",
                restrict_components: true,
                component_whitelist: ["page_config"],
                id: "test-field-id-1",
              },
              body: {
                type: "bloks",
                id: "test-field-id-2",
                pos: 1,
              },
            },
            image: null,
            preview_field: null,
            is_root: true,
            preview_tmpl: null,
            is_nestable: false,
            all_presets: [],
            preset_id: null,
            real_name: "test-component",
            component_group_uuid: null,
            color: null,
            icon: null,
            internal_tags_list: [],
            internal_tag_ids: [],
            content_type_asset_preview: null,
            metadata: {},
          },
        },
      },
    },
  ],
};

export default config;
