import type { ResourceIntegrationTestConfig } from "src/tests/resource-integration.test";
import StoryResourceCollectionRestoreService from "../services/StoryResourceCollectionRestoreService";
import { ResourceType } from "@core/types/types";

const config: ResourceIntegrationTestConfig = {
  name: "Simple Stories",
  description: "Test basic story restoration without parent dependencies",
  ServiceClass: StoryResourceCollectionRestoreService,
  initialMappingRegistry: {},
  resources: [
    {
      input: {
        id: 100001,
        name: "test-story-1",
        slug: "test-story-1",
        full_slug: "test-story-1",
        parent_id: 0,
        is_folder: false,
        published: true,
        content: {
          _uid: "test-uid-1",
          component: "page",
          body: [],
        },
        created_at: "2025-01-01T00:00:00.000Z",
        updated_at: "2025-01-01T00:00:00.000Z",
        published_at: "2025-01-01T00:00:00.000Z",
        first_published_at: "2025-01-01T00:00:00.000Z",
        last_author_id: 100001,
        position: 0,
        tag_list: [],
        alternates: [],
        translated_slugs: [],
        localized_paths: [],
        translated_stories: [],
        breadcrumbs: [],
        user_ids: [],
        space_role_ids: [],
        group_id: "test-group-id-1",
        uuid: "test-uuid-1",
        path: null,
        default_root: null,
        disble_fe_editor: false,
        disable_fe_editor: false,
        parent: null,
        is_startpage: false,
        unpublished_changes: false,
        meta_data: null,
        imported_at: null,
        pinned: false,
        publish_at: null,
        expire_at: null,
        can_not_view: false,
        is_scheduled: null,
        scheduled_dates: null,
        ideas: [],
        stage: null,
        favourite_for_user_ids: [],
        deleted_at: null,
        sort_by_date: null,
        last_author: {
          id: 100001,
          userid: "test-user-1",
          friendly_name: "Test User 1",
        },
      },
      expectedApiCall: {
        endpointSuffix: "stories",
        body: {
          story: {
            id: 100001,
            name: "test-story-1",
            slug: "test-story-1",
            full_slug: "test-story-1",
            parent_id: 0,
            is_folder: false,
            published: true,
            content: {
              _uid: "test-uid-1",
              component: "page",
              body: [],
            },
            created_at: "2025-01-01T00:00:00.000Z",
            updated_at: "2025-01-01T00:00:00.000Z",
            published_at: "2025-01-01T00:00:00.000Z",
            first_published_at: "2025-01-01T00:00:00.000Z",
            last_author_id: 100001,
            position: 0,
            tag_list: [],
            alternates: [],
            translated_slugs: [],
            localized_paths: [],
            translated_stories: [],
            breadcrumbs: [],
            user_ids: [],
            space_role_ids: [],
            group_id: "test-group-id-1",
            uuid: "test-uuid-1",
            path: null,
            default_root: null,
            disble_fe_editor: false,
            disable_fe_editor: false,
            parent: null,
            is_startpage: false,
            unpublished_changes: false,
            meta_data: null,
            imported_at: null,
            pinned: false,
            publish_at: null,
            expire_at: null,
            can_not_view: false,
            is_scheduled: null,
            scheduled_dates: null,
            ideas: [],
            stage: null,
            favourite_for_user_ids: [],
            deleted_at: null,
            sort_by_date: null,
            last_author: {
              id: 100001,
              userid: "test-user-1",
              friendly_name: "Test User 1",
            },
          },
          force_update: 1,
          publish: 1,
        },
      },
      mockResponse: {
        data: {
          story: {
            id: 200001, // New ID after restoration
            name: "test-story-1",
            slug: "test-story-1",
            full_slug: "test-story-1",
            parent_id: 0,
            is_folder: false,
            published: true,
            content: {
              _uid: "test-uid-1",
              component: "page",
              body: [],
            },
            created_at: "2025-01-01T00:00:00.000Z",
            updated_at: "2025-01-01T00:00:00.000Z",
            published_at: "2025-01-01T00:00:00.000Z",
            first_published_at: "2025-01-01T00:00:00.000Z",
            last_author_id: 100001,
            position: 0,
            tag_list: [],
            alternates: [],
            translated_slugs: [],
            localized_paths: [],
            translated_stories: [],
            breadcrumbs: [],
            user_ids: [],
            space_role_ids: [],
            group_id: "test-group-id-1",
            uuid: "test-uuid-1",
            path: null,
            default_root: null,
            disble_fe_editor: false,
            disable_fe_editor: false,
            parent: null,
            is_startpage: false,
            unpublished_changes: false,
            meta_data: null,
            imported_at: null,
            pinned: false,
            publish_at: null,
            expire_at: null,
            can_not_view: false,
            is_scheduled: null,
            scheduled_dates: null,
            ideas: [],
            stage: null,
            favourite_for_user_ids: [],
            deleted_at: null,
            sort_by_date: null,
            last_author: {
              id: 100001,
              userid: "test-user-1",
              friendly_name: "Test User 1",
            },
          },
        },
      },
    },
    {
      input: {
        id: 100002,
        name: "test-story-2",
        slug: "test-story-2",
        full_slug: "test-story-2",
        parent_id: 0,
        is_folder: true,
        published: true,
        content: {
          body: [],
          component: "page",
        },
        created_at: "2025-01-01T00:00:00.000Z",
        updated_at: "2025-01-01T00:00:00.000Z",
        published_at: "2025-01-01T00:00:00.000Z",
        first_published_at: "2025-01-01T00:00:00.000Z",
        last_author_id: 100002,
        position: 0,
        tag_list: [],
        alternates: [],
        translated_slugs: [],
        localized_paths: [],
        translated_stories: [],
        breadcrumbs: [],
        user_ids: [],
        space_role_ids: [],
        group_id: "test-group-id-2",
        uuid: "test-uuid-2",
        path: null,
        default_root: "page",
        disble_fe_editor: true,
        disable_fe_editor: true,
        parent: null,
        is_startpage: false,
        unpublished_changes: false,
        meta_data: null,
        imported_at: null,
        pinned: false,
        publish_at: null,
        expire_at: null,
        can_not_view: false,
        is_scheduled: null,
        scheduled_dates: null,
        ideas: [],
        stage: null,
        favourite_for_user_ids: [],
        deleted_at: null,
        sort_by_date: null,
        last_author: {
          id: 100002,
          userid: "test-user-2",
          friendly_name: "Test User 2",
        },
      },
      expectedApiCall: {
        endpointSuffix: "stories",
        body: {
          story: {
            id: 100002,
            name: "test-story-2",
            slug: "test-story-2",
            full_slug: "test-story-2",
            parent_id: 0,
            is_folder: true,
            published: true,
            content: {
              body: [],
              component: "page",
            },
            created_at: "2025-01-01T00:00:00.000Z",
            updated_at: "2025-01-01T00:00:00.000Z",
            published_at: "2025-01-01T00:00:00.000Z",
            first_published_at: "2025-01-01T00:00:00.000Z",
            last_author_id: 100002,
            position: 0,
            tag_list: [],
            alternates: [],
            translated_slugs: [],
            localized_paths: [],
            translated_stories: [],
            breadcrumbs: [],
            user_ids: [],
            space_role_ids: [],
            group_id: "test-group-id-2",
            uuid: "test-uuid-2",
            path: null,
            default_root: "page",
            disble_fe_editor: true,
            disable_fe_editor: true,
            parent: null,
            is_startpage: false,
            unpublished_changes: false,
            meta_data: null,
            imported_at: null,
            pinned: false,
            publish_at: null,
            expire_at: null,
            can_not_view: false,
            is_scheduled: null,
            scheduled_dates: null,
            ideas: [],
            stage: null,
            favourite_for_user_ids: [],
            deleted_at: null,
            sort_by_date: null,
            last_author: {
              id: 100002,
              userid: "test-user-2",
              friendly_name: "Test User 2",
            },
          },
          force_update: 1,
          publish: 1,
        },
      },
      mockResponse: {
        data: {
          story: {
            id: 200002, // New ID after restoration
            name: "test-story-2",
            slug: "test-story-2",
            full_slug: "test-story-2",
            parent_id: 0,
            is_folder: true,
            published: true,
            content: {
              body: [],
              component: "page",
            },
            created_at: "2025-01-01T00:00:00.000Z",
            updated_at: "2025-01-01T00:00:00.000Z",
            published_at: "2025-01-01T00:00:00.000Z",
            first_published_at: "2025-01-01T00:00:00.000Z",
            last_author_id: 100002,
            position: 0,
            tag_list: [],
            alternates: [],
            translated_slugs: [],
            localized_paths: [],
            translated_stories: [],
            breadcrumbs: [],
            user_ids: [],
            space_role_ids: [],
            group_id: "test-group-id-2",
            uuid: "test-uuid-2",
            path: null,
            default_root: "page",
            disble_fe_editor: true,
            disable_fe_editor: true,
            parent: null,
            is_startpage: false,
            unpublished_changes: false,
            meta_data: null,
            imported_at: null,
            pinned: false,
            publish_at: null,
            expire_at: null,
            can_not_view: false,
            is_scheduled: null,
            scheduled_dates: null,
            ideas: [],
            stage: null,
            favourite_for_user_ids: [],
            deleted_at: null,
            sort_by_date: null,
            last_author: {
              id: 100002,
              userid: "test-user-2",
              friendly_name: "Test User 2",
            },
          },
        },
      },
    },
  ],
  expectedFinalMappingRegistry: {
    [ResourceType.STORIES]: {
      oldIdToNewIdMap: {
        100001: 200001, // First story mapping
        100002: 200002, // Second story mapping
      },
      oldUuidToNewUuidMap: {
        "test-uuid-1": "test-uuid-1",
        "test-uuid-2": "test-uuid-2",
      },
    },
  },
};

export default config;
